// initial_exercise_data.dart
import 'package:fitnesss_tracker_app/db/Models/exercise_model.dart';

final List<Exercise> initialExercises = [
  //----------------------------------------------------
  // BODYWEIGHT EXERCISES (WARM-UP/CARDIO)
  //----------------------------------------------------
  Exercise(
    name: 'Jumping Jacks',
    category: 'Warm-up',
    primaryMuscleGroups: ['Full Body'],
    equipment: 'Bodyweight',
    type: 'Rep',
    difficulty: 'Beginner',
    imagePath: 'assets/EXERCISE ICON/JUMPING JACKS.gif',
    detectorPath: 'lib/body_posture/exercises/jumping_jacks.dart',
  ),
  Exercise(
    name: 'Arm Circles (Clockwise)',
    category: 'Warm-up',
    primaryMuscleGroups: ['Shoulders', 'Arms'],
    equipment: 'Bodyweight',
    type: 'Rep',
    difficulty: 'Beginner',
    imagePath: 'assets/EXERCISE ICON/ARM CIRCLE CLOCKWISE(1).gif',
    detectorPath: 'lib/body_posture/exercises/arm_circles_clockwise.dart',
  ),
  Exercise(
    name: 'Arm Circles (Counter-Clockwise)',
    category: 'Warm-up',
    primaryMuscleGroups: ['Shoulders', 'Arms'],
    equipment: 'Bodyweight',
    type: 'Rep',
    difficulty: 'Beginner',
    imagePath: 'assets/EXERCISE ICON/ARM CIRCLE COUNTER-CLOCKWISE.gif',
    detectorPath:
        'lib/body_posture/exercises/arm_circles_counterclockwise.dart',
  ),
  Exercise(
    name: 'Alternating Hooks',
    category: 'Cardio',
    primaryMuscleGroups: ['Shoulders', 'Core'],
    equipment: 'Bodyweight',
    type: 'Rep',
    difficulty: 'Beginner',
    imagePath: 'assets/EXERCISE ICON/ALTERNATING HOOKS.gif',
    detectorPath: 'lib/body_posture/exercises/altemating_hooks.dart',
  ),
  Exercise(
    name: 'Side Hop',
    category: 'Cardio',
    primaryMuscleGroups: ['Legs', 'Glutes'],
    equipment: 'Bodyweight',
    type: 'Rep',
    difficulty: 'Beginner',
    imagePath: 'assets/EXERCISE ICON/SIDE HOP.gif',
    detectorPath: 'lib/body_posture/exercises/side_hop.dart',
  ),
  Exercise(
    name: 'Inchworms',
    category: 'Warm-up',
    primaryMuscleGroups: ['Full Body'],
    equipment: 'Bodyweight',
    type: 'Rep',
    difficulty: 'Intermediate',
    imagePath: 'assets/EXERCISE ICON/INCHWORMS.gif',
    detectorPath: 'lib/body_posture/exercises/inchworm.dart',
  ),
  //----------------------------------------------------
  // BODYWEIGHT EXERCISES (CORE)
  //----------------------------------------------------
  Exercise(
    name: 'Abdominal Crunches',
    category: 'Strength',
    primaryMuscleGroups: ['Abs'],
    equipment: 'Bodyweight',
    type: 'Rep',
    difficulty: 'Beginner',
    imagePath: 'assets/EXERCISE ICON/ABDOMINAL CRUNCHES.gif',
    detectorPath: 'lib/body_posture/exercises/abdominal_crunches.dart',
  ),
  Exercise(
    name: 'Leg Raises',
    category: 'Strength',
    primaryMuscleGroups: ['Lower Abs'],
    equipment: 'Bodyweight',
    type: 'Rep',
    difficulty: 'Beginner',
    imagePath: 'assets/EXERCISE ICON/LEG RAISES.gif',
    detectorPath: 'lib/body_posture/exercises/leg_raises.dart',
  ),
  Exercise(
    name: 'Russian Twist',
    category: 'Strength',
    primaryMuscleGroups: ['Obliques'],
    equipment: 'Bodyweight',
    type: 'Rep',
    difficulty: 'Beginner',
    imagePath: 'assets/EXERCISE ICON/RUSSIAN TWIST.gif',
    detectorPath: 'lib/body_posture/exercises/russian_twist.dart',
  ),
  Exercise(
    name: 'Plank',
    category: 'Strength',
    primaryMuscleGroups: ['Full Body', 'Abs'],
    equipment: 'Bodyweight',
    type: 'Timer',
    difficulty: 'Beginner',
    imagePath: 'assets/EXERCISE ICON/PLANK.gif',
    detectorPath: 'lib/body_posture/exercises/plank.dart',
  ),
  //----------------------------------------------------
  // BODYWEIGHT EXERCISES (UPPER BODY)
  //----------------------------------------------------
  Exercise(
    name: 'Push-Ups',
    category: 'Strength',
    primaryMuscleGroups: ['Chest', 'Triceps', 'Shoulders'],
    equipment: 'Bodyweight',
    type: 'Reps',
    difficulty: 'Intermediate',
    imagePath: 'assets/EXERCISE ICON/PUSH-UPS.gif',
    detectorPath: 'lib/body_posture/exercises/push_up.dart',
  ),
  Exercise(
    name: 'Diamond Push-Ups',
    category: 'Strength',
    primaryMuscleGroups: ['Triceps', 'Chest'],
    equipment: 'Bodyweight',
    type: 'Rep',
    difficulty: 'Advanced',
    imagePath: 'assets/EXERCISE ICON/DIAMOND PUSH-UPS.gif',
    detectorPath: 'lib/body_posture/exercises/diamond_pushup.dart',
  ),
  Exercise(
    name: 'Triceps Dips',
    category: 'Strength',
    primaryMuscleGroups: ['Triceps', 'Chest'],
    equipment: 'Bodyweight',
    type: 'Rep',
    difficulty: 'Intermediate',
    imagePath: 'assets/EXERCISE ICON/TRICEPS DIPS.gif',
    detectorPath: 'lib/body_posture/exercises/tricep_dips.dart',
  ),
  Exercise(
    name: 'Knee Push-Ups',
    category: 'Strength',
    primaryMuscleGroups: ['Chest', 'Triceps'],
    equipment: 'Bodyweight',
    type: 'Rep',
    difficulty: 'Beginner',
    imagePath: 'assets/EXERCISE ICON/KNEE PUSH-UPS.gif',
    detectorPath: 'lib/body_posture/exercises/knee_pushup.dart',
  ),
  Exercise(
    name: 'Decline Push-Ups',
    category: 'Strength',
    primaryMuscleGroups: ['Upper Chest', 'Shoulders', 'Triceps'],
    equipment: 'Bodyweight',
    type: 'Rep',
    difficulty: 'Advanced',
    imagePath: 'assets/EXERCISE ICON/DECLINE PUSH-UPS.gif',
    detectorPath: 'lib/body_posture/exercises/decline_pushup.dart',
  ),
  Exercise(
    name: 'Arm Raises',
    category: 'Warm-up',
    primaryMuscleGroups: ['Shoulders'],
    equipment: 'Bodyweight',
    type: 'Rep',
    difficulty: 'Beginner',
    imagePath: 'assets/EXERCISE ICON/ARM RAISES.gif',
    detectorPath: 'lib/body_posture/exercises/arm_raises.dart',
  ),
  Exercise(
    name: 'Rhomboid Pulls',
    category: 'Warm-up',
    primaryMuscleGroups: ['Upper Back'],
    equipment: 'Bodyweight',
    type: 'Rep',
    difficulty: 'Beginner',
    imagePath: 'assets/EXERCISE ICON/RHOMBOID PULLS.gif',
    detectorPath: 'lib/body_posture/exercises/rhomboid_pulls.dart',
  ),
  Exercise(
    name: 'Incline Push-Ups',
    category: 'Strength',
    primaryMuscleGroups: ['Chest', 'Shoulders'],
    equipment: 'Bodyweight',
    type: 'Rep',
    difficulty: 'Beginner',
    imagePath: 'assets/EXERCISE ICON/INCLINE PUSH-UPS.gif',
    detectorPath: 'lib/body_posture/exercises/incline_pushup.dart',
  ),
  Exercise(
    name: 'Pike Push-Ups',
    category: 'Strength',
    primaryMuscleGroups: ['Shoulders', 'Triceps'],
    equipment: 'Bodyweight',
    type: 'Rep',
    difficulty: 'Advanced',
    imagePath: 'assets/EXERCISE ICON/PIKE PUSH UPS.gif',
    detectorPath: 'lib/body_posture/exercises/pike_pushup.dart',
  ),
  //----------------------------------------------------
  // BODYWEIGHT EXERCISES (LOWER BODY)
  //----------------------------------------------------
  Exercise(
    name: 'Squats',
    category: 'Strength',
    primaryMuscleGroups: ['Quads', 'Glutes', 'Hamstrings'],
    equipment: 'Bodyweight',
    type: 'Rep',
    difficulty: 'Beginner',
    imagePath: 'assets/EXERCISE ICON/SQUATS.gif',
    detectorPath: 'lib/body_posture/exercises/bwsquatdart.dart',
  ),
  Exercise(
    name: 'Lunges',
    category: 'Strength',
    primaryMuscleGroups: ['Quads', 'Glutes', 'Hamstrings'],
    equipment: 'Bodyweight',
    type: 'Rep',
    difficulty: 'Intermediate',
    imagePath: 'assets/EXERCISE ICON/LUNGES_.gif',
    detectorPath: 'lib/body_posture/exercises/lunges.dart',
  ),
  Exercise(
    name: 'Jumping Squats',
    category: 'Strength',
    primaryMuscleGroups: ['Quads', 'Glutes', 'Hamstrings'],
    equipment: 'Bodyweight',
    type: 'Rep',
    difficulty: 'Advanced',
    imagePath: 'assets/EXERCISE ICON/JUMPING SQUATS.gif',
    detectorPath: 'lib/body_posture/exercises/jumping_squat.dart',
  ),
  Exercise(
    name: 'Donkey Kicks (Right)',
    category: 'Strength',
    primaryMuscleGroups: ['Glutes'],
    equipment: 'Bodyweight',
    type: 'Rep',
    difficulty: 'Beginner',
    imagePath: 'assets/EXERCISE ICON/DONKEY KICKS RIGHT.gif',
    detectorPath: 'lib/body_posture/exercises/donkeykicks_right.dart',
  ),
  Exercise(
    name: 'Donkey Kicks (Left)',
    category: 'Strength',
    primaryMuscleGroups: ['Glutes'],
    equipment: 'Bodyweight',
    type: 'Rep',
    difficulty: 'Beginner',
    imagePath: 'assets/EXERCISE ICON/DONKEY KICKS LEFT.gif',
    detectorPath: 'lib/body_posture/exercises/donkeykicks_left.dart',
  ),
  Exercise(
    name: 'Glute Kickbacks (Right)',
    category: 'Strength',
    primaryMuscleGroups: ['Glutes'],
    equipment: 'Bodyweight',
    type: 'Rep',
    difficulty: 'Beginner',
    imagePath: 'assets/EXERCISE ICON/GLUTE KICK BACK RIGHT.gif',
    detectorPath: 'lib/body_posture/exercises/glutekickback_right.dart',
  ),
  Exercise(
    name: 'Glute Kickbacks (Left)',
    category: 'Strength',
    primaryMuscleGroups: ['Glutes'],
    equipment: 'Bodyweight',
    type: 'Rep',
    difficulty: 'Beginner',
    imagePath: 'assets/EXERCISE ICON/GLUTE KICK BACK LEFT.gif',
    detectorPath: 'lib/body_posture/exercises/glutekickback_left.dart',
  ),
  Exercise(
    name: 'Wall Sit',
    category: 'Stretch',
    primaryMuscleGroups: ['Quads', 'Glutes'],
    equipment: 'Bodyweight',
    type: 'Timer',
    difficulty: 'Beginner',
    imagePath: 'assets/EXERCISE ICON/WALL SIT.gif',
    detectorPath: 'lib/body_posture/exercises/wall_sit.dart',
  ),
  //----------------------------------------------------
  // BODYWEIGHT EXERCISES (STRETCH/COOLDOWN)
  //----------------------------------------------------
  Exercise(
    name: 'Cobra Stretch',
    category: 'Stretch',
    primaryMuscleGroups: ['Core', 'Back'],
    equipment: 'Bodyweight',
    type: 'Timer',
    difficulty: 'Beginner',
    imagePath: 'assets/EXERCISE ICON/COBRA STRETCH.gif',
    detectorPath: 'lib/body_posture/exercises/cobra_stretch.dart',
  ),
  Exercise(
    name: 'Triceps Stretch (Right)',
    category: 'Stretch',
    primaryMuscleGroups: ['Triceps'],
    equipment: 'Bodyweight',
    type: 'Timer',
    difficulty: 'Beginner',
    imagePath: 'assets/EXERCISE ICON/TRICEPS STRETCH RIGHT.gif',
    detectorPath: 'lib/body_posture/exercises/tricep_stretch_right.dart',
  ),
  Exercise(
    name: 'Triceps Stretch (Left)',
    category: 'Stretch',
    primaryMuscleGroups: ['Triceps'],
    equipment: 'Bodyweight',
    type: 'Timer',
    difficulty: 'Beginner',
    imagePath: 'assets/EXERCISE ICON/TRICEPS STRETCH LEFT.gif',
    detectorPath: 'lib/body_posture/exercises/tricep_stretch_left.dart',
  ),
  Exercise(
    name: 'Standing Biceps Stretch (Right)',
    category: 'Stretch',
    primaryMuscleGroups: ['Biceps'],
    equipment: 'Bodyweight',
    type: 'Timer',
    difficulty: 'Beginner',
    imagePath: 'assets/EXERCISE ICON/STANDING BICEPS STRETCH RIGHT.gif',
    detectorPath: 'lib/body_posture/exercises/standing_bicepstretchright.dart',
  ),
  Exercise(
    name: 'Standing Biceps Stretch (Left)',
    category: 'Stretch',
    primaryMuscleGroups: ['Biceps'],
    equipment: 'Bodyweight',
    type: 'Timer',
    difficulty: 'Beginner',
    imagePath: 'assets/EXERCISE ICON/STANDING BICEPS STRETCH LEFT.gif',
    detectorPath: 'lib/body_posture/exercises/standing_bicep_stretchleft.dart',
  ),
  Exercise(
    name: 'Knee to Chest Stretch (Right)',
    category: 'Stretch',
    primaryMuscleGroups: ['Lower Back', 'Glutes'],
    equipment: 'Bodyweight',
    type: 'Timer',
    difficulty: 'Beginner',
    imagePath: 'assets/EXERCISE ICON/KNEE TO CHEST STRETCH RIGHT.gif',
    detectorPath: 'lib/body_posture/exercises/knee_to_chest_right.dart',
  ),
  Exercise(
    name: 'Knee to Chest Stretch (Left)',
    category: 'Stretch',
    primaryMuscleGroups: ['Lower Back', 'Glutes'],
    equipment: 'Bodyweight',
    type: 'Timer',
    difficulty: 'Beginner',
    imagePath: 'assets/EXERCISE ICON/KNEE TO CHEST STRETCH LEFT.gif',
    detectorPath: 'lib/body_posture/exercises/knee_to_chest_left.dart',
  ),
  Exercise(
    name: 'Calf Stretch (Left)',
    category: 'Stretch',
    primaryMuscleGroups: ['Calves'],
    equipment: 'Bodyweight',
    type: 'Timer',
    difficulty: 'Beginner',
    imagePath: 'assets/EXERCISE ICON/CALF STRETCH LEFT.gif',
    detectorPath: 'lib/body_posture/exercises/calf_stretch_left.dart',
  ),
  Exercise(
    name: 'Calf Stretch (Right)',
    category: 'Stretch',
    primaryMuscleGroups: ['Calves'],
    equipment: 'Bodyweight',
    type: 'Timer',
    difficulty: 'Beginner',
    imagePath: 'assets/EXERCISE ICON/CALF STRETCH RIGHT.gif',
    detectorPath: 'lib/body_posture/exercises/calf_stretch_right.dart',
  ),
  Exercise(
    name: 'Cat Cow Pose',
    category: 'Stretch',
    primaryMuscleGroups: ['Spine', 'Core'],
    equipment: 'Bodyweight',
    type: 'Rep',
    difficulty: 'Beginner',
    imagePath: 'assets/EXERCISE ICON/CAT COW POSE.gif',
    detectorPath: 'lib/body_posture/exercises/catcow_posedart.dart',
  ),
  Exercise(
    name: 'Child\'s Pose',
    category: 'Stretch',
    primaryMuscleGroups: ['Back', 'Hips'],
    equipment: 'Bodyweight',
    type: 'Timer',
    difficulty: 'Beginner',
    imagePath: 'assets/EXERCISE ICON/CHILD_S POSE.gif',
    detectorPath: 'lib/body_posture/exercises/childpose.dart',
  ),
  //----------------------------------------------------
  // DUMBBELL EXERCISES
  //----------------------------------------------------
  Exercise(
    name: 'Dumbbell Split Squat (Right)',
    category: 'Strength',
    primaryMuscleGroups: ['Quads', 'Glutes', 'Hamstrings'],
    equipment: 'Dumbbells',
    type: 'Rep',
    difficulty: 'Intermediate',
    imagePath:
        'assets/DUMBBELL EXERCISES/DumbbellSplitsquatRight-ezgif.com-resize.gif',
    detectorPath: 'lib/body_posture/dumbbells/umbbell_splitsquat_right.dart',
  ),
  Exercise(
    name: 'Dumbbell Split Squat (Left)',
    category: 'Strength',
    primaryMuscleGroups: ['Quads', 'Glutes', 'Hamstrings'],
    equipment: 'Dumbbells',
    type: 'Rep',
    difficulty: 'Intermediate',
    imagePath:
        'assets/DUMBBELL EXERCISES/DumbbellSplitsquatLeft-ezgif.com-resize.gif',
    detectorPath: 'lib/body_posture/dumbbells/umbbell_splitsquat_left.dart',
  ),
  Exercise(
    name: 'Dumbbell Squats',
    category: 'Strength',
    primaryMuscleGroups: ['Quads', 'Glutes', 'Hamstrings'],
    equipment: 'Dumbbells',
    type: 'Rep',
    difficulty: 'Intermediate',
    imagePath: 'assets/DUMBBELL EXERCISES/DumbbellSquats-ezgif.com-resize.gif',
    detectorPath: 'lib/body_posture/dumbbells/umbbell_squat.dart',
  ),
  Exercise(
    name: 'Valley Press',
    category: 'Strength',
    primaryMuscleGroups: ['Chest', 'Triceps'],
    equipment: 'Dumbbells',
    type: 'Rep',
    difficulty: 'Intermediate',
    imagePath: 'assets/DUMBBELL EXERCISES/ValleyPress-ezgif.com-resize.gif',
    detectorPath: 'lib/body_posture/dumbbells/alley_press.dart',
  ),
  Exercise(
    name: 'Dumbbell Chest Fly',
    category: 'Strength',
    primaryMuscleGroups: ['Chest'],
    equipment: 'Dumbbells',
    type: 'Rep',
    difficulty: 'Intermediate',
    imagePath:
        'assets/DUMBBELL EXERCISES/DumbbellChestFly-ezgif.com-resize.gif',
    detectorPath: 'lib/body_posture/dumbbells/umbbell_chestfly.dart',
  ),
  Exercise(
    name: 'Bent Over Row',
    category: 'Strength',
    primaryMuscleGroups: ['Back', 'Biceps'],
    equipment: 'Dumbbells',
    type: 'Rep',
    difficulty: 'Intermediate',
    imagePath: 'assets/DUMBBELL EXERCISES/BentOverRow.gif',
    detectorPath: 'lib/body_posture/dumbbells/bentover_row.dart',
  ),
  Exercise(
    name: 'Standing Dumbbell Curl',
    category: 'Strength',
    primaryMuscleGroups: ['Biceps'],
    equipment: 'Dumbbells',
    type: 'Rep',
    difficulty: 'Intermediate',
    imagePath:
        'assets/DUMBBELL EXERCISES/Standingdumbbellcurl-ezgif.com-resize.gif',
    detectorPath: 'lib/body_posture/dumbbells/nding_dumbellcurLdart.dart',
  ),
  Exercise(
    name: 'Dumbbell Kickbacks',
    category: 'Strength',
    primaryMuscleGroups: ['Triceps'],
    equipment: 'Dumbbells',
    type: 'Rep',
    difficulty: 'Intermediate',
    imagePath:
        'assets/DUMBBELL EXERCISES/Dumbellkickbacks-ezgif.com-resize.gif',
    detectorPath: 'lib/body_posture/dumbbells/umbbell_kickback.dart',
  ),
  Exercise(
    name: 'Dumbbell Drag Curl',
    category: 'Strength',
    primaryMuscleGroups: ['Biceps'],
    equipment: 'Dumbbells',
    type: 'Rep',
    difficulty: 'Intermediate',
    imagePath: 'assets/DUMBBELL EXERCISES/dragcurl.gif',
    detectorPath: 'lib/body_posture/dumbbells/ragcurl.dart',
  ),
  Exercise(
    name: 'Dumbbell Crunch',
    category: 'Strength',
    primaryMuscleGroups: ['Abs'],
    equipment: 'Dumbbells',
    type: 'Rep',
    difficulty: 'Intermediate',
    imagePath:
        'assets/DUMBBELL EXERCISES/DumbbellCrunches-ezgif.com-resize.gif',
    detectorPath: 'lib/body_posture/dumbbells/umbbell_crunches.dart',
  ),
  Exercise(
    name: 'Dumbbell Russian Twist',
    category: 'Strength',
    primaryMuscleGroups: ['Obliques', 'Abs'],
    equipment: 'Dumbbells',
    type: 'Rep',
    difficulty: 'Intermediate',
    imagePath:
        'assets/DUMBBELL EXERCISES/DumbellRussianTwist-ezgif.com-resize.gif',
    detectorPath: 'lib/body_posture/dumbbells/umbbell_russiantwist.dart',
  ),
];
