workflows:
  unsigned-ios-app-build:
    name: Unsigned iOS App Build
    # Use a powerful machine for a faster build
    instance_type: mac_mini_m2 
    
    environment:
      flutter: stable
      # Define your build version (You can change 1.0.0 and 1)
      vars:
        BUILD_NAME: 1.0.0
        BUILD_NUMBER: 1
      xcode: latest
      cocoapods: default

    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter packages pub get
      
      - name: Build the unsigned iOS app
        script: |
          # This command builds the iOS app and explicitly disables code signing.
          flutter build ios --no-codesign \
            --release \
            --build-name=$BUILD_NAME \
            --build-number=$BUILD_NUMBER \
            --export-options-plist=$CM_EXPORT_OPTIONS_PATH
            
      - name: Zip the .app for easy download
        script: |
          # The resulting app is inside this path. We zip it so we can download one file.
          cd build/ios/iphoneos
          zip -r app_output.zip Runner.app
          
    artifacts:
      # This tells Codemagic to keep the .zip file with our unsigned app
      - build/ios/iphoneos/app_output.zip
